Repository Ecuador-In-Tech/web, pull requests merged in 2025-01, with the labels that each got.

#27 Community Card Component #23
  public/herux.png
  public/icons/github.svg
  public/icons/instagram.svg
  public/icons/linkedin.svg
  public/kernel-chaos.png
  public/wordpress.png
  src/assets/communities.json
  src/components/CardCommunity.astro
  src/components/CommunityCard/Avatar.astro
  src/components/CommunityCard/CommunityCard.astro
  src/components/CommunityCard/SocialLinks.astro
  src/components/CommunityCard/Tags.astro
  src/interfaces/communities.ts
  src/pages/communities.astro
Labels: enhancement

#21 Implement dprint and biome as a linter and formatter
  .github/workflows/deploy.yml
  .vscode/extensions.json
  .vscode/launch.json
  README.md
  astro.config.mjs
  biome.json
  dprint.json
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/assets/commitments.json
  src/assets/common-questions.json
  src/assets/communities.json
  src/assets/events.json
  src/components/AboutUs.astro
  src/components/CardBase.astro
  src/components/CardCommunity.astro
  src/components/CardEvent.astro
  src/components/CommunityCard/Avatar.astro
  src/components/CommunityCard/CommunityCard.astro
  src/components/CommunityCard/SocialLinks.astro
  src/components/CommunityCard/Tags.astro
  src/components/Faq.astro
  src/components/Features.astro
  src/components/Footer.astro
  src/components/Navbar.astro
  src/interfaces/communities.ts
  src/interfaces/events.ts
  src/layouts/Layout.astro
  src/pages/communities.astro
  src/pages/events.astro
  src/pages/index.astro
  src/pages/rss.xml.js
  src/styles/globals.css
  tailwind.config.mjs
  tsconfig.json
Labels: enhancement

#31 Hero section redesign
  src/components/Hero.astro
Labels: enhancement

#30 Footer rebasement and best practices
  src/components/AboutUs.astro
  src/components/Footer.astro
Labels: enhancement

#32 `Faq.astro` migration to dropdown
  public/icons/downIcon.svg
  src/components/Accordion.astro
  src/components/Faq.astro
  src/styles/globals.css
Labels: enhancement, help wanted

#35 Navbar rebasement
  public/icons/burgerMenu.svg
  public/icons/closeIcon.svg
  src/components/Navbar.astro
  src/components/Navbar/Link.astro
  src/components/Navbar/Navbar.astro
  src/components/Navbar/OffcanvasMenu.astro
  src/layouts/Layout.astro
  src/styles/globals.css
Labels: enhancement

#40 analytics: add umami tracking code
  src/layouts/Layout.astro
Labels: enhancement

#43 About section rebasement
  public/images/codefest_conference.jpg
  public/images/hacktoberfest.jpg
  src/assets/home-sections.json
  src/components/AboutSection.astro
  src/components/AboutUs.astro
  src/components/CardEvent.astro
  src/components/Faq.astro
  src/components/Footer.astro
  src/components/Navbar/Navbar.astro
  src/components/shared/Button.astro
  src/enums/button-type.enum.ts
  src/interfaces/button.interface.ts
  src/layouts/Layout.astro
  src/pages/index.astro
  src/styles/globals.css
Labels: enhancement

#47 Feat: Event Details page
  public/banner_events.png
  src/assets/events.json
  src/components/CardBase.astro
  src/components/CardEvent.astro
  src/interfaces/events.ts
  src/pages/event/[id].astro
  src/pages/events.astro
  src/styles/globals.css
Labels: enhancement

#51 Repo maintenance 2025 01 21
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/assets/communities.json
  src/components/CardBase.astro
  src/components/CardEvent.astro
  src/components/CommunityCard/CommunityCard.astro
  src/pages/event/[id].astro
  src/pages/events.astro
  src/styles/globals.css
Labels: enhancement, dependencies

#52 Add new DEVCON event
  public/devcon_gye_2025.jpg
  src/assets/events.json
  src/components/CardEvent.astro
Labels: enhancement

#53 Add Contributors Page
  pnpm-lock.yaml
  public/icons/youtube.svg
  public/images/people/agustina.png
  public/images/people/brayen.png
  public/images/people/dav.png
  public/images/people/ivan.png
  public/images/people/jhon.png
  public/images/people/nataly.png
  src/assets/contributors.json
  src/assets/events.json
  src/assets/home-sections.json
  src/components/AboutSection.astro
  src/components/CardBase.astro
  src/components/CardEvent.astro
  src/components/CommunityCard/CommunityCard.astro
  src/components/HallOfFame/ContributorItem.astro
  src/components/HallOfFame/HallOfFame.astro
  src/components/shared/SocialLinks.astro
  src/interfaces/common.ts
  src/interfaces/communities.ts
  src/pages/event/[id].astro
  src/pages/events.astro
  src/pages/thanks.astro
  src/styles/globals.css
Labels: enhancement

#57 Commitements section redesign
  public/icons/leftIcon.svg
  public/icons/meeting.svg
  public/icons/shared.svg
  public/icons/volt.svg
  public/images/shared_resources.jpg
  public/images/volunteering.jpg
  src/assets/commitments.json
  src/assets/home-sections.json
  src/components/CommitementsCarrousel/Carrousel.astro
  src/components/CommitementsCarrousel/CarrouselItem.astro
  src/components/CommitementsCarrousel/Icon.astro
  src/components/Features.astro
Labels: enhancement

#58 Binary images to webp
  public/banner_events.png
  public/banner_events.webp
  public/devcon_gye_2025.jpg
  public/devcon_gye_2025.webp
  public/dotnet.png
  public/dotnet.webp
  public/favicon.png
  public/favicon.webp
  public/funpython.jpg
  public/funpython.webp
  public/gdg_gye.png
  public/gdg_gye.webp
  public/github-workshop.jpg
  public/github-workshop.webp
  public/herux.png
  public/herux.webp
  public/images/codefest_conference.jpg
  public/images/codefest_conference.webp
  public/images/hacktoberfest.jpg
  public/images/hacktoberfest.webp
  public/images/people/agustina.png
  public/images/people/agustina.webp
  public/images/people/brayen.png
  public/images/people/brayen.webp
  public/images/people/dav.png
  public/images/people/dav.webp
  public/images/people/ivan.png
  public/images/people/ivan.webp
  public/images/people/jhon.png
  public/images/people/jhon.webp
  public/images/people/nataly.png
  public/images/people/nataly.webp
  public/kernel-chaos.png
  public/kernel-chaos.webp
  public/path_to_impact_1.webp
  public/path_to_impact_2.jpg
  public/path_to_impact_2.webp
  public/path_to_impact_3.jpg
  public/path_to_impact_3.webp
  public/wordpress.png
  public/wordpress.webp
  src/assets/communities.json
  src/assets/contributors.json
  src/assets/events.json
  src/assets/home-sections.json
  src/components/AboutSection.astro
  src/components/CommunityCard/CommunityCard.astro
  src/layouts/Layout.astro
  src/pages/event/[id].astro
Labels: enhancement
